### ISSUE TITLE
affected_rows -1 question

### ISSUE THREAD

**Issue by quasiperfect** [EFTEC/DaoOne#3]
Hi,

Any idea why would affected_rows return -1 even if it updates the row correctly ?

my code is like this
```
       $values['updated_at'] = date('Y-m-d H:i:s');

        try
	{
		$dao = new \eftec\DaoOne($database['host'], $database['username'], $database['password'], $database['name'], 'log.log');
		$dao->connect();

		$dao->from('table_name');
                

		foreach ($values as $k => $v)
		{
			$dao->set($k . "=?", ['s', $v]);
		}

		$dao->where('id=?', ['i', $row]);

		return $dao->update();
	}
	catch (Exception $e)
	{
		return NULL;
	}
```

update i changed to
```
                $result = $dao->update();

		var_dump(mysqli_info($dao->conn1));

		return $result;
```
and i get string(40) "Rows matched: 1 Changed: 1 Warnings: 0"
so mysqli_info returns correct results

**Comment by jorgecc** [comment]
Ok, I added a new version 3.29  

The main problem is it relies on https://www.php.net/manual/en/mysqli.affected-rows.php  but it is called after we close the statement. Now, we store the information before it is closed.
